name: Analytics
type: Drupal CMS
description: Sets up the Google Tag module to track the traffic of your website using Google Analytics and Google Tag Manager.

install:
  - google_tag

input:
  property_id:
    data_type: string
    description: "The Google Tag, in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    constraints:
      NotBlank: []
      Regex: '/^(?:GT|UA|G|AW|DC|GTM)-[0-9a-zA-Z]{4,}(?:-[0-9]{1,})?$/'
    prompt:
      method: ask
      arguments:
        question: "Enter the Google Tag ID for tracking. This ID is unique to each site you want to track separately, and must be in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    form:
      '#type': 'textfield'
      '#title': 'Google Tag ID'
      '#description': "The Google Tag ID for tracking. This ID is unique to each site you want to track separately, and must be in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    default:
      source: value
      value: ''

config:
  strict: false
  import:
    google_tag: '*'
  actions:
    google_tag.settings:
      simpleConfigUpdate:
        default_google_tag_entity: drupal
    google_tag.container.drupal:
      set:
        property_name: tag_container_ids
        value:
          - ${property_id}
